import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faAlignLeft,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faBan,
  faBook,
  faBullhorn,
  faCheck,
  faChevronCircleLeft,
  faChevronLeft,
  faChevronCircleRight,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCode,
  faEdit,
  faEquals,
  faHeart,
  faInfo,
  faInfoCircle,
  faKey,
  faLightbulb,
  faNewspaper,
  faPlus,
  faQuestion,
  faThList,
  faTimesCircle,
  faTrashAlt,
  faUserCircle,
  faUserEdit,
  faUserShield
} from '@fortawesome/free-solid-svg-icons';

import {
  faCalendar as farCalendar,
  faCheckSquare,
  faHeart as farHeart,
  faSave,
  faSquare
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faAlignLeft,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faBan,
  faBook,
  faBullhorn,
  farCalendar,
  faCheck,
  faCheckSquare,
  faChevronCircleLeft,
  faChevronLeft,
  faChevronCircleRight,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCode,
  faEdit,
  faEquals,
  faHeart,
  farHeart,
  faInfo,
  faInfoCircle,
  faKey,
  faLightbulb,
  faNewspaper,
  faPlus,
  faQuestion,
  faSave,
  faSquare,
  faThList,
  faTimesCircle,
  faTrashAlt,
  faUserCircle,
  faUserEdit,
  faUserShield
);

export default library;
